from configs.elementsData import ElementsData

class JumpData:
    pop_window_set = {
        "AquariumCommonFishChangePanel",
        "BaitAndRodShowPanel",
        "ChampointshipResultPopup",
        "DailyTipsPanel",
        "DivisionChangePanel",
        "EventSignSevenDayPanel",
        "FishAlbumPreviewPanel",
        "FishBagPanel",
        "FisheryGiftPackPanel",
        "FisheryUnlockPanel",
        "FlashCardReceivePanel",
        "LeaderBoardPopResultPanel",
        # "NBG_prepare_2_album_01(Clone)",
        "PlayerLevelupPanel",
        "PVENewbieGiftPackPanel",
        "PVPBoosterGiftPackPanel",
        "Recharge1And1Panel",
        "BattleTreasureMapPanel",
        "MessageBoxPanel",
    }

    panel_close_dict = {
        "AchievementGroupPanel": [ElementsData.AchievementGroup.btn_close],
        "AchievementWantedPanel":[ElementsData.AchievementWanted.btn_close],
        "AchievementCategoryPanel": [ElementsData.AchievementCategory.btn_close],
        "AchievementPanel": [ElementsData.Achievement.btn_close],
        "AquariumPanel": [ElementsData.Aquarium.btn_close],
        "AquariumCommonFishChangePanel": [ElementsData.AquariumCommonFishChange.btn_close],
        "AquariumFishPanel":[ElementsData.AquariumFish.btn_close],
        "BaitAndRodAlbumPanel": [ElementsData.BaitAndRodAlbum.btn_close],
        "BaitAndRodShowPanel": [ElementsData.BaitAndRodShow.tap_to_continue],
        "BattleExplainPanel": [ElementsData.BattleExplain.close],
        "BattleFailedPanel": [ElementsData.BattleFailed.btn_again],
        "BattlePassBuyLevelPanel": [ElementsData.BattlePassBuyLevel.btn_close],
        "BattlePassBuyLicensePanel": [ElementsData.BattlePassBuyLicense.btn_close],
        "BattlePassIntroPanel": [ElementsData.BattlePassIntro.panel1to2Btn, ElementsData.BattlePassIntro.panel2to3Btn,ElementsData.BattlePassIntro.btn_go],
        "BattlePassPanel": [ElementsData.BattlePass.btn_close],
        "BattlePassPopPanel": [ElementsData.BattlePassPop.btn_close],
        "BattlePassRewardPanel": [ElementsData.BattlePassReward.btn_close],
        "BattlePreparePanel": [ElementsData.BattlePrepare.btn_close],
        "BattleTreasureMapPanel":[ElementsData.BattleTreasureMap.btn_close],
        "BuyEnergyPanel": [ElementsData.BuyEnergy.btn_close],
        "ChampointshipResultPopup": [ElementsData.ChampointshipResult.btn_close],
        "CommonWebViewPanel":[ElementsData.CommonWebView.btn_close],
        "DailyTipsPanel": [ElementsData.DailyTips.btn_close],
        "DivisionChangePanel": [ElementsData.DivisionChange.tap_to_close],
        "DivisionLeaderboardPanel":[ElementsData.DivisionLeaderboard.btn_close],
        "DivisionListPanel":[ElementsData.DivisionList.btn_close],
        "DLCDownloadPanel": [ElementsData.DLCDownload.btn_close],
        "EventSignSevenDayPanel":[ElementsData.EventSignSevenDay.btn_receive, ElementsData.Rewards.tap_to_claim],
        "FishAlbum3DPanel":[ElementsData.FishAlbum3D.btn_close],
        "FishAlbumPreviewPanel": [ElementsData.FishAlbumPreview.btn_close],
        "FishBagPanel": [ElementsData.FishBag.btn_close, ElementsData.FishBag.btn_next],
        "FishCardGiftPackCustomizePanel": [ElementsData.FishCardGiftPackCustomize.btn_close],
        "FishCardPanel": [ElementsData.FishCard.btn_close],
        "FlashCardReceivePanel": [ElementsData.FlashCardReceive.btn_close],
        "FisheryGiftPackPanel": [ElementsData.FisheryGiftPack.btn_close],
        "FisheryUnlockPanel": [ElementsData.FisheryUnlock.btn_close],
        "FishCardUpgradePanel": [ElementsData.FishCardUpgrade.btn_close],
        "GearPanel": [ElementsData.Gear.btn_close],
        "GearLevelupPanel":[ElementsData.GearLevelup.btn_close],
        "GearEnhancePanel":[ElementsData.GearEnhance.btn_close],
        "GearEnhanceSuccesPanel":[ElementsData.GearEnhanceSucces.btn_close],
        "IAAPanel": [ElementsData.IAA.btn_close],
        "LeaderBoardPopResultPanel": [ElementsData.LeaderBoardPopResult.btn_claim],
        "MailPanel": [ElementsData.Mail.btn_close],
        "MessageBoxPanel": [ElementsData.MessageBox.btn_confirm],
        "NewbieTaskPanel":[ElementsData.NewbieTask.btn_close],
        # "NBG_prepare_2_album_01(Clone)": [ElementsData.NewbieGuide.NBG_prepare_2_album_01, ElementsData.NewbieGuide.NBG_prepare_2_album_02, ElementsData.NewbieGuide.NBG_prepare_2_album_03, ElementsData.NewbieGuide.NBG_album_01, ElementsData.NewbieGuide.NBG_album_02, ElementsData.NewbieGuide.NBG_album_03, ElementsData.NewbieGuide.NBG_prepare_weak_01],
        "PartySalePanel":[ElementsData.PartySale.btn_close],
        "PlayerInfoPanel": [ElementsData.PlayerInfo.btn_close_additional, ElementsData.PlayerInfo.btn_confirm, ElementsData.PlayerInfo.btn_close],
        "PlayerSettingPanel": [ElementsData.PlayerSetting.btn_close_additional, ElementsData.PlayerSetting.btn_close],
        "PlayerLevelupPanel": [ElementsData.PlayerLevelup.tap_to_continue],
        "PVPBoosterGiftPackPanel": [ElementsData.PVPBoosterGiftPack.btn_close],
        "ProgressRewardsPanel":[ElementsData.ProgressRewards.btn_close],
        "PVENewbieGiftPackPanel":[ElementsData.PVENewbieGiftPack.btn_close],
        "PVPHallPanel": [ElementsData.PVPHall.btn_close],
        "PVPResultPanel": [ElementsData.PVPResult.tap_to_close],
        "PVPRuleTipsPanel": [ElementsData.PVPRuleTips.btn_close],
        "QuestionnairePanel": [ElementsData.Questionnaire.btn_close],
        "RankPanel": [ElementsData.Rank.btn_close],
        "RankFishLeaderboardPanel": [ElementsData.RankFishLeaderboard.btn_close],
        "Recharge1And1Panel": [ElementsData.Recharge1And1.btn_close],
        "RechargeBlack5Panel": [ElementsData.RechargeBlack5.btn_close],
        "RechargeEndlessPanel": [ElementsData.RechargeEndless.btn_close],
        "ResultPanel": [ElementsData.Result.btn_claim],
        "RewardsPanel": [ElementsData.Rewards.tap_to_claim],
        "RodMoreToOnePanel": [ElementsData.RodMoreToOne.btn_close],
        "RoulettePanel": [ElementsData.Roulette.btn_close],
        "StorePanel": [ElementsData.Store.btn_close],
        "TaskFishingCareerPanel": [ElementsData.TaskFishingCareer.btn_close],
        "TaskPanel": [ElementsData.Task.btn_close],
        "TournamentsPanel": [ElementsData.Tournaments.btn_close],
        "TreasureChestGearsShardsPanel": [ElementsData.TreasureChestGearsShards.btn_close],
        "TreasureChestPanel": [ElementsData.TreasureChest.btn_close],
        "TreasureChestRewardsPanel": [ElementsData.TreasureChestRewards.btn_close]
    }

    panel_open_dict = {
        "AchievementPanel": [ElementsData.Home.btn_achievement],
        "AquariumPanel": [ElementsData.Home.btn_aquarium],
        "BattlePassPanel": [ElementsData.Home.btn_bp],
        "BaitAndRodAlbumPanel": [ElementsData.Home.btn_gears],
        "BuyEnergyPanel": [ElementsData.Home.btn_add_100500],
        "DivisionLeaderboardPanel": [ElementsData.Home.btn_pve, ElementsData.Tournaments.btn_leaderboard],
        "DLCDownloadPanel": [ElementsData.Home.btn_download],
        "FishAlbum3DPanel": [ElementsData.Home.btn_fishalbum],
        "FishCardPanel": [ElementsData.Home.btn_fishcard],
        "FisheryGiftPackPanel": [ElementsData.Home.btn_event_location],
        "GearPanel": [ElementsData.Home.btn_gears],
        "MailPanel": [ElementsData.Home.btn_mail],
        "NewbieTaskPanel": [ElementsData.Home.btn_rookie3days],
        "PlayerSettingPanel": [ElementsData.Home.player_info, ElementsData.PlayerInfo.btn_setting],
        "PlayerInfoPanel":[ElementsData.Home.player_info],
        "ProgressRewardsPanel": [ElementsData.Home.btn_globa_progress],
        "PVPHallPanel": [ElementsData.Home.btn_pvp],
        "QuestionnairePanel": [ElementsData.Home.btn_questionnaire],
        "RankPanel": [ElementsData.Home.btn_fishranking],
        "Recharge1And1Panel": [ElementsData.Home.btn_1add1],
        "RechargeBlack5Panel": [ElementsData.Home.btn_black5],
        "RechargeEndlessPanel": [ElementsData.Home.btn_endless],
        "RoulettePanel": [ElementsData.Home.btn_pve, ElementsData.Tournaments.btn_turntable],
        "StorePanel": [ElementsData.Home.btn_store],
        "TaskPanel": [ElementsData.Home.btn_bp,ElementsData.BattlePassReward.btn_close, ElementsData.BattlePassIntro.next1to2,  ElementsData.BattlePassIntro.next2to3, ElementsData.BattlePassIntro.btn_go, ElementsData.BattlePass.btn_task],
        "TournamentsPanel": [ElementsData.Home.btn_pve],
        "TreasureChestPanel": [ElementsData.Home.btn_chest],
    }

    # 与panel_open_dict项保持一致
    panel_dict = {
        "AchievementPanel": ElementsData.Achievement.AchievementPanel,
        "AquariumPanel": ElementsData.Aquarium.AquariumPanel,
        "BattlePassPanel": ElementsData.BattlePass.BattlePassPanel,
        "BaitAndRodAlbumPanel": ElementsData.BaitAndRodAlbum.BaitAndRodAlbumPanel,
        "BuyEnergyPanel": ElementsData.BuyEnergy.BuyEnergyPanel,
        "DivisionLeaderboardPanel":ElementsData.DivisionLeaderboard.DivisionLeaderboardPanel,
        "DLCDownloadPanel": ElementsData.DLCDownload.DLCDownloadPanel,
        "FishAlbum3DPanel": ElementsData.FishAlbum3D.FishAlbum3DPanel,
        "FishCardPanel": ElementsData.FishCard.FishCardPanel,
        "FisheryGiftPackPanel": ElementsData.FisheryGiftPack.FisheryGiftPackPanel,
        "GearPanel": ElementsData.Gear.GearPanel,
        "MailPanel": ElementsData.Mail.MailPanel,
        "NewbieTaskPanel": ElementsData.NewbieTask.NewbieTaskPanel,
        "PlayerSettingPanel": ElementsData.PlayerSetting.PlayerSettingPanel,
        "PlayerInfoPanel": ElementsData.PlayerInfo.PlayerInfoPanel,
        "ProgressRewardsPanel": ElementsData.ProgressRewards.ProgressRewardsPanel,
        "PVPHallPanel": ElementsData.PVPHall.PVPHallPanel,
        "QuestionnairePanel": ElementsData.Questionnaire.QuestionnairePanel,
        "RankPanel": ElementsData.Rank.RankPanel,
        "Recharge1And1Panel": ElementsData.Recharge1And1.Recharge1And1Panel,
        "RechargeBlack5Panel": ElementsData.RechargeBlack5.RechargeBlack5Panel,
        "RechargeEndlessPanel": ElementsData.RechargeEndless.RechargeEndlessPanel,
        "RoulettePanel": ElementsData.Roulette.RoulettePanel,
        "StorePanel": ElementsData.Store.StorePanel,
        "TaskPanel": ElementsData.Task.TaskPanel,
        "TournamentsPanel": ElementsData.Tournaments.TournamentsPanel,
        "TreasureChestPanel": ElementsData.TreasureChest.TreasureChestPanel
    }